source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'Notification_Example', :exclusive => true do
  pod "Notification", :path => "../"
end

target 'Notification_Tests', :exclusive => true do
  pod "Notification", :path => "../"

  pod 'Specta'
  pod 'Expecta'
end
